library(MetaMicrobiome)
data <- read.csv("../data/Baxter_16_alpha_data.csv")
head(data)
thresVetor <- getthresholds(dataset=data, c("Shannon", "Observe", "J"), type="median")
print(thresVetor)
highlowVector <- high_low_vector(var_of_interest="Shannon", dataset=data, threshold=thresVetor)
print(highlowVector)
multiVector <- MultiHighLow(var_of_interest=c("Shannon", "Observe", "J"), dataset=data, threshold=thresVetor)
print(multiVector)
